version: "3.7"
services:
  influx:
    image: influxdb:1.8.0
    volumes:
      - ./.data/influx:/var/lib/influxdb
    ports:
      - 8086:8086

  grafana:
    image: grafana/grafana:6.7.3
    ports:
      - 23000:3000
    volumes:
      - ./.data/grafana:/var/lib/grafana
